[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
name = "alltrue-customer-sdk"
readme = "README.md"
dynamic = ["version"]
authors = [
    {name = "AllTrue.ai INC", email = "ury@alltrue.ai"}
]
description = "Client SDK for AllTrue.ai API"
dependencies = [
    "openai~=1.63.0",
    "wrapt~=1.17.2",
]
requires-python = ">= 3.11"

[project.urls]
Repository = "https://github.com/AllTrue-ai/alltrue-customer-sdk"

[project.optional-dependencies]
testing = [
    "fastapi~=0.111.1",
    "mitmproxy~=11.0.2",
    "nest-asyncio~=1.6.0",
]
dev = [
    "build",
    "pre-commit",
]
full = [
    "alltrue-customer-core @ file:///${PROJECT_ROOT}/core",
    "alltrue-customer-sdk[testing]",
    "alltrue-customer-sdk[dev]",
]

[tool.pdm.version]
source = "file"
path = "src/version.py"

[tool.pdm.build]
includes = ["src/alltrue"]
custom-hook = "src/build.py"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = [
    "-o log_cli=true",
    "-o log_cli=info",
    "-o consider_namespace_packages=true",
    "--import-mode=importlib",
]
asyncio_mode = "auto"
markers = [
    "skip_on_aws: marks tests to be skipped on AWS",
]
pythonpath = [
    "src",
    "core/src",
]
