name: upload assets to release

on:
  release:
    types: [ created ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false
jobs:
  aws-non-concurrent-build-job:
    timeout-minutes: 35
    runs-on:
      labels: [self-hosted, linux]
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        run: |
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/test-machine-ssh
          python3.11 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -e.[full]
      - name: Check
        run: |
          source venv/bin/activate
          pre-commit run --all-files
      - name: Test
        run: |
          source venv/bin/activate
          pytest -m "not skip_on_aws" --maxfail=5 --durations=10
      - name: Build
        run: |
          source venv/bin/activate
          python -m build
      - name: Upload
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/*
