name: upload assets to release

on:
  release:
    types: [ created ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false
jobs:
  aws-non-concurrent-build-job:
    timeout-minutes: 35
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Build
        run: |
          pip install -e.[full]
          pre-commit run --all-files
          pytest -m "not skip_on_aws" --maxfail=5 --durations=10
          python -m build
      - name: Upload
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/*
