name: run tests on aws machine

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore: # Ignore changes to markdown files
      - '**.md'
      - '**.service'
      - '**.timer'
      - '**.sh'
      - 'docs/**'
      - 'github_runners_service_files/**'
# Cancel previous runs of this workflow if a new run is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  test-pull-request:
    timeout-minutes: 35
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Setup
        run: |
          echo "ALLTRUE_API_URL=https://api.alltrue-be.com" > .env
          echo "ALLTRUE_API_KEY=${{ secrets.API_KEY }}" >> .env
          echo "ALLTRUE_CUSTOMER_ID=${{ secrets.CUSTOMER_ID }}" >> .env
          echo "ALLTRUE_ENDPOINT_IDENTIFIER=${{ secrets.ENDPOINTER_IDENTIFIER }}" >> .env
          echo "CONFIG_LLM_API_PROVIDER=any" >> .env
      - name: Test
        run: |
          pip install -e.[full]
          pip install pytest-md-report
          pre-commit autoupdate --repo https://github.com/pre-commit/pre-commit-hooks
          pre-commit run --all-files
          pytest -m "not skip_on_aws" --maxfail=5 --durations=10 --md-report --md-report-flavor github --md-report-output test_report.md
      - name: Report
        uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ hashFiles('test_report.md') != '' }}
        with:
          header: test-report
          recreate: true
          path: 'test_report.md'
